[package]
name = "coins-android-bug-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
coins-ledger = { git = "https://github.com/summa-tx/coins", rev = "1d578d4e00e24bdd5e4c89174c105107f3469931" }
hex = "0.4.3"
hex-literal = "0.4.1"
tokio = { version = "1.34.0", features = ["full"] }
